# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
 - title: Anatomy of a Beekeeper
email: coletteisabella@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bees, art, science and tech, this is the site for the continuing adventures of Colette Isabella.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://coletteisabella" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: coletteisabella
github_username:  coletteisabella

# Build settings
markdown: kramdown
theme: minima
plugins:
  #- jekyll-feed
  #- jekyll-mentions
  #- jemoji
  #- jekyll-redirect-from
  #- jekyll-sitemap

#build settings
#navigation:
  - text: about
    url: about/

  - text: friends
    url: friends/

  - text: bees
    url: bees/

  - text: games
    url: games/

  - text: projects
    url: projects/

  #- text: shop
  #  url: shop/

#- text: patreon
 #   url: patreon/

# bundle exec jekyll serve


disqus_short_name: cisabella
disqus_show_comment_count: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


